version: '3.8'

services:
  neo4j:
    image: neo4j:5.20.0-community
    hostname: neo4j
    ports:
      - "7687:7687"
      - "7474:7474"
    volumes:
      - ./neo4j_data:/data
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_db_fs_store_root_path=/data
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes

  fastctx:
    build: .
    ports:
      - "8000:8000"
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=password
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - neo4j
    volumes:
      - .:/app

  test_runner:
    build: .
    command: uv run pytest
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=password
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - neo4j
    volumes:
      - .:/app
