[project]
name = "time-server"
version = "0.1.0"
description = "Simple MCP server for time utilities"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp[cli]>=1.10.1",
    "uvicorn>=0.24.0",
    "fastapi>=0.104.0",
]
