services:
  neo4j:
    image: neo4j:5.15-community
    container_name: neo4j-db
    environment:
      - NEO4J_AUTH=neo4j/password123
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.*
    ports:
      - "7474:7474" # HTTP
      - "7687:7687" # Bolt
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    networks:
      - neo4j-network
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "cypher-shell -u neo4j -p password123 'RETURN 1' || exit 1",
        ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python-app
    env_file: ".env"
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=password123
    ports:
      - "8000:8000"
    depends_on:
      neo4j:
        condition: service_healthy

    volumes:
      - "../Java-Hello-World-Enterprise-Edition/:/demo"
    networks:
      - neo4j-network
    profiles:
      - app
    # restart: unless-stopped

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:

networks:
  neo4j-network:
    driver: bridge
